name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/github.com/katydid/validator-go-relaxng
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install xmllint
      run: |
        sudo apt install -y libxml2-utils
    - name: Simplify TestSuite
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make testsuite
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24
    - name: Fetch dependencies
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        go mod download -x
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Build
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make build
    - name: Format
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make fmt
    - name: Vet
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make vet
    - name: Test
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make test
    - name: Diff
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make diff
    - name: Check license
      run: |
        cd gopath/github.com/katydid/validator-go-relaxng
        make checklicense